export const FETCH_PEOPLE='FETCH_PEOPLE';
export const FETCH_PLANETS='FETCH_PLANETS';
export const FETCH_FILMS='FETCH_FILMS';
export const FETCH_SPECIES='FETCH_SPECIES';
export const FETCH_VEHICLES='FETCH_VEHICLES';
export const FETCH_STARSHIPS='FETCH_STARSHIPS';
export const FETCH_DATA='FETCH_DATA';
export const OPEN_MENU='OPEN_MENU';
export const CLOSE_MENU='CLSOE_MENU';
export const GET_FILM_NAME='GET_FILM_NAME';

